spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bio_marketplace
    username: root
    password: sql77777
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  messages:
    hello: Hello from Bio-Marketplace Digital Ocean application!
  servlet:
    context-path: /api
