spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true


  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:

  confirm-url-prefix: "https://farmvibe-app-2u9sj.ondigitalocean.app/api/confirm/"

server:
  messages:
    hello: Hello from Bio-Marketplace application!
  servlet:
    context-path: /api

jwt:
  jwtAtSecret: ${JWT_AT_SECRET:3b4b2f2822144afa49ace61e650775809579816de5e6b170ff3911931fb717ed}
  jwtRtSecret: ${JWT_RT_SECRET:3b4b2f2822144afa49ace61e650775809579816de5e6b170ff3911931fb717aB}
  atExpirationInMs: ${JWT_AT_EXPIRATION_IN_MS:1200000}
  rtExpirationInMs: ${JWT_RT_EXPIRATION_IN_MS:86400000}
  atCookieName: access-token
  rtCookieName: refresh-token
